# Generated by Django 4.2.3 on 2023-07-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showname", models.CharField(max_length=200)),
                ("concerthall", models.CharField(max_length=200)),
                ("sido", models.CharField(max_length=200)),
                ("gugun", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
            ],
        ),
    ]
