# Generated by Django 4.2.3 on 2023-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=10000)),
                ('genre', models.CharField(default='classic', max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('runtime', models.IntegerField(default=100)),
                ('day', models.IntegerField(default=3)),
            ],
        ),
    ]
