# Generated by Django 4.2.3 on 2023-07-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_up", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
