# Generated by Django 4.2.3 on 2023-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_up", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("showname", models.CharField(max_length=200)),
                ("concerthall", models.CharField(max_length=200)),
                ("sido", models.CharField(max_length=200)),
                ("gugun", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("price", models.IntegerField(null=True)),
                ("age", models.IntegerField(null=True)),
                ("runtime", models.IntegerField(null=True)),
                ("period", models.IntegerField(null=True)),
                ("cluster", models.IntegerField(null=True)),
            ],
        ),
    ]
