# Generated by Django 4.2.3 on 2023-07-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_up", "0002_alter_show_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="show", name="age", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="show", name="cluster", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="show", name="period", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="show", name="price", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="show", name="runtime", field=models.IntegerField(null=True),
        ),
    ]
